# dripkit cava config

[general]
framerate = 60
bars = 0
bar_width = 2
bar_spacing = 1

[input]
method = pipewire
source = auto

[output]
method = ncurses

[color]
gradient = 1
gradient_count = 6
gradient_color_1 = '{{teal}}'
gradient_color_2 = '{{blue}}'
gradient_color_3 = '{{accent}}'
gradient_color_4 = '{{mauve}}'
gradient_color_5 = '{{pink}}'
gradient_color_6 = '{{red}}'

[smoothing]
noise_reduction = 77
