# dripkit dunst theme

[global]
    width = 350
    height = 150
    offset = 20x20
    origin = top-right
    transparency = 0
    frame_color = "{{accent}}"
    frame_width = 2
    corner_radius = 12
    font = {{font}} 11
    padding = 12
    horizontal_padding = 16
    icon_position = left
    max_icon_size = 48
    separator_color = auto
    gap_size = 8
    background = "{{bg}}"
    foreground = "{{fg}}"

[urgency_low]
    background = "{{bg}}"
    foreground = "{{fg}}"
    frame_color = "{{surface1}}"
    timeout = 5

[urgency_normal]
    background = "{{bg}}"
    foreground = "{{fg}}"
    frame_color = "{{accent}}"
    timeout = 10

[urgency_critical]
    background = "{{bg}}"
    foreground = "{{fg}}"
    frame_color = "{{red}}"
    timeout = 0
